- .pre-commit-config.yaml
- README.md
- meta/main.yml
- Add pre-commit hooks for linting
- Also limits scope to Linux to start with
> Add pre-commit hooks

- roles/falcon/tasks/api.yml
- roles/falcon/tasks/install.yml
- roles/falcon/tasks/uninstall.yml
Adds install and uninstall tasks. Still WIP because all the sub-commands are oddly different across different OSes.
> Add tasks for macos

- roles/falcon_installation/defaults/main.yml
- roles/falcon_installation/tasks/preinstall.yml
> Remove hardcoded tmp

- .github/workflows/ansible-lint.yml
Let's only run linting on PRs and not also pushes which duplicates the linting.
> Fix Ansible linting for collections

- roles/falcon_installation/tasks/install.yml
- roles/falcon_installation/tasks/preinstall.yml
Ran into some Layer 8 issues. Apologies for closing out the previous pull request. 
Hopefully this is what you need here.
> Fixing issue with variable conditionals

- roles/falcon_installation/tasks/install.yml
> Fix condition for `falcon_provisioning_token`

- galaxy.yml
- roles/falcon_installation/README.md
- roles/falcon_installation/defaults/main.yml
- roles/falcon_installation/tasks/install.yml
- roles/falcon_installation/tasks/main.yml
- roles/falcon_installation/tasks/preinstall.yml
- roles/falcon_installation/tasks/url.yml
- roles/falcon_installation/tasks/win_api.yml
- roles/falcon_installation/tasks/win_install.yml
- roles/falcon_installation/tasks/win_uninstall.yml
- tests/ansible-lint.conf
- Add windows support
- Fix minor formatting differences
- Unify package naming
> Add Windows support

- README.md
- roles/falcon_installation/tasks/install.yml
- roles/falcon_installation/tasks/preinstall.yml
- roles/falcon_installation/tasks/uninstall.yml
- Cleanup macOS tasks
- Update README for apple's new MDM direction
> Finalize macOS tasks

- meta/runtime.yml
Another oblique requirement by ansible galaxy importing service
> Add runtime.yml

- .github/workflows/falcon_installation.yml
- molecule/falcon_installation/converge.yml
- roles/falcon_installation/README.md
- roles/falcon_installation/defaults/main.yml
- roles/falcon_installation/tasks/api.yml
- roles/falcon_installation/tasks/install.yml
- roles/falcon_installation/tasks/preinstall.yml
- roles/falcon_installation/tasks/win_api.yml
- roles/falcon_installation/vars/main.yml
This is a backwards incompatible change that will be reflected in a new major release version.
> Update vars to match standard naming

- roles/falcon_installation/README.md
- roles/falcon_installation/defaults/main.yml
- roles/falcon_installation/tasks/api.yml
- roles/falcon_installation/tasks/preinstall.yml
- roles/falcon_installation/tasks/win_api.yml
- Makes the API query more readable
- Fixes #60
- Fixes #22
> Update and simplify API calls

- roles/falcon_installation/README.md
- roles/falcon_installation/defaults/main.yml
- roles/falcon_installation/tasks/api.yml
- roles/falcon_installation/tasks/preinstall.yml
- roles/falcon_installation/tasks/win_api.yml
- Rename to falcon_sensor_version_decrement to better reflect N-x support
> Rename falcon_sensor_version variable

- .github/workflows/falcon_uninstall.yml
- molecule/falcon_uninstall/converge.yml
- molecule/falcon_uninstall/molecule.yml
- molecule/falcon_uninstall/prepare.yml
- molecule/falcon_uninstall/verify.yml
- Added the falcon_uninstall role to the molecule testing framework
- Added the GH Actions workflow to support testing the role
- Added actual verifications to each role to make it more robust
> Adding uninstall role to molecule/workflow

- roles/falcon_installation/README.md
- roles/falcon_installation/defaults/main.yml
- roles/falcon_installation/tasks/api.yml
- roles/falcon_installation/tasks/win_api.yml
- roles/falcon_installation/vars/main.yml
> Enable cloud region autodiscovery

- .github/workflows/ansible-test.yml
- .github/workflows/falcon_installation.yml
- .github/workflows/falcon_uninstall.yml
- roles/falcon_installation/handlers/main.yml
- roles/falcon_installation/tasks/install.yml
Using the new falconctl module to replace the Linux falconctl command tasks.
> Updating tasks to use new module

- README.md
closes #109 
* Adds falcon_configure role to main collection README
> Updated README to reflect new falcon_configure role

- roles/falcon_install/README.md
- roles/falcon_install/defaults/main.yml
- roles/falcon_install/tasks/win_install.yml
> Add missing var causing windows installs to fail

- galaxy.yml
- plugins/modules/falconctl.py
Causes error during automation hub export, plus this is not really needed.
> Removed doc frag extend

- .github/workflows/win_falcon_configure.yml
- .github/workflows/win_falcon_install.yml
- .github/workflows/win_falcon_uninstall.yml
Trying to use GH actions caching to speed up Windows CI jobs with Vagrant.
> Gh actions caching

- .github/workflows/falcon_configure.yml
- .github/workflows/falcon_install.yml
- .github/workflows/falcon_uninstall.yml
- .github/workflows/win_falcon_configure.yml
- .github/workflows/win_falcon_install.yml
- .github/workflows/win_falcon_uninstall.yml
Allows us to getter better test coverage/visibility on both the Ansible side, as well as ensuring new falcon-sensors don't break any functionality.
> For better coverage, run ci daily

- plugins/module_utils/falconctl_utils.py
- plugins/modules/falconctl_info.py
> add rfm-state|reason to falconctl_info module

- .github/workflows/falcon_configure.yml
- .github/workflows/falcon_install.yml
- .github/workflows/falcon_uninstall.yml
- .github/workflows/win_falcon_configure.yml
- .github/workflows/win_falcon_install.yml
- .github/workflows/win_falcon_uninstall.yml
- molecule/falcon_configure/molecule.yml
- molecule/falcon_install/molecule.yml
- molecule/falcon_uninstall/molecule.yml
- Updates GH workflow files to better support push vs pull_request_target event types
- Update molecule instance naming conventions to support local GH workflow testing and for better visibility
> Changes to support better GH workflow logic surrounding pull_request_target

- galaxy.yml
- roles/falcon_install/tasks/api.yml
Fixes #189 
- Add ztl module supported to kernel compat check
- bumps version
> 189 add ztl module supported kernel compat

- roles/falcon_install/README.md
- roles/falcon_uninstall/README.md
URL for defaults/main.yml had `default` instead of `defaults`
> Minor fix with url to defaults file

- .gitignore
- README.md
- changelogs/config.yaml
- plugins/modules/falconctl.py
- plugins/modules/falconctl_info.py
To prepare for Automation Hub requirement and follow Ansible's developer guidelines for collections.
> Ansible collection changelog requirement

- README.md
- docs/crowdstrike.falcon.falconctl_info_module.rst
- docs/crowdstrike.falcon.falconctl_module.rst
Falcon Modules docs have been added + link to them via collection README
> Added docs + updates to README

- .github/workflows/ansible-test.yml
- .github/workflows/falcon_configure.yml
- .github/workflows/falcon_install.yml
- .github/workflows/falcon_uninstall.yml
Ubuntu-18 runner will soon be deprecated
> Update workflows with latest version of ubuntu runner

- changelogs/fragments/232-auth-in-download.yml
- roles/falcon_install/README.md
- roles/falcon_install/defaults/main.yml
- roles/falcon_install/tasks/url.yml
> support for auth in download

- .github/workflows/pages.yml
GitHub Action used to build docs and push them to gh-pages branch
> New workflow for building docs

- .github/workflows/falcon_configure.yml
- .github/workflows/falcon_install.yml
- .github/workflows/falcon_uninstall.yml
- changelogs/fragments/233-fix-rhel9-support-issue.yml
- roles/falcon_install/tasks/preinstall.yml
closes #226 
- Fixes api change with RHEL9 support
- Adds RHEL9 testing to molecule
> Fix rhel os family target

- .github/workflows/pages.yml
small changes to pages wf:
- Allow manual runs (useful for testing purposes)
- Remove path, this should be run on main push to ensure docs are always updated
> Minor change to pages workflow - allow manual run

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/228-fix-apd-billing-issue.yml
- changelogs/fragments/231-fix-falconctl-plugin-issues.yml
- changelogs/fragments/232-auth-in-download.yml
- changelogs/fragments/233-fix-rhel9-support-issue.yml
- galaxy.yml
New release, which includes new changelog
> bump version to 3.2.19

- .pylintrc
- plugins/doc_fragments/credentials.py
- plugins/module_utils/falconpy_utils.py
- plugins/modules/example_template.py
- plugins/modules/sensor_download.py
- requirements.txt
This is the initial design preview for v4.0.0
This PR should include:
- Updated README to explain new changes
- New helper function in module_utils that starts with handling auth validation for falconpy
- New doc fragment for credentials that can be used in modules\
The current sensor_downloads module here is just for example purposes. This will be removed and added in a subsequent PR.
> Initial helper and doc updates for next major release

- .devcontainer/requirements.txt
- .github/workflows/falcon_configure.yml
- .github/workflows/falcon_install.yml
- .github/workflows/falcon_uninstall.yml
- .github/workflows/win_falcon_configure.yml
- .github/workflows/win_falcon_install.yml
- .github/workflows/win_falcon_uninstall.yml
- .pre-commit-config.yaml
- LICENSE
- roles/falcon_configure/tasks/configure.yml
- roles/falcon_configure/tasks/main.yml
- roles/falcon_configure/tests/inventory
- roles/falcon_install/files/falcon-sensor.gpg
- roles/falcon_install/tasks/main.yml
- roles/falcon_install/tasks/preinstall.yml
- roles/falcon_uninstall/tasks/main.yml
- roles/falcon_uninstall/tasks/uninstall.yml
- roles/falcon_uninstall/tests/inventory
- tests/inventory
Support the latest ansible-lint updates and pre-commit updates
> Updating workflows to use latest version of ansible-lint

- roles/falcon_configure/tasks/main.yml
- roles/falcon_uninstall/tasks/win_uninstall.yml
closes #180 
- Fix issue with regex finding sensor to uninstall
- Fix when clause for falcon_configure on windows
> Win ci updates

- roles/falcon_install/tasks/preinstall.yml
- roles/falcon_install/vars/main.yml
Fixes #280 #278 
This PR introduces changes to support the addition of the s390x arch for the Falcon sensor.
- Created a new dictionary to manage API query by `ansible_architecture`
> Fixes issue with s390x support

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
Includes fix for s390x arch support using the sensor installer API
> Bump version 3.2.25

- .github/workflows/falcon_install_policy.yml
- .github/workflows/win_falcon_install_policy.yml
- molecule/falcon_install_policy/cleanup.yml
- molecule/falcon_install_policy/converge.yml
- molecule/falcon_install_policy/molecule.yml
- molecule/falcon_install_policy/prepare.yml
- molecule/falcon_install_policy/verify.yml
- molecule/win_falcon_install_policy/INSTALL.md
- molecule/win_falcon_install_policy/cleanup.yml
- molecule/win_falcon_install_policy/converge.yml
- molecule/win_falcon_install_policy/molecule.yml
- molecule/win_falcon_install_policy/prepare.yml
- molecule/win_falcon_install_policy/verify.yml
Closes #277 
This PR add a new test suite for Linux/Windows to ensure we test the sensor update policy blocks.
> Add sensor update policy test suite

- meta/runtime.yml
> Use new 2.11.x format to update lint syntax

- roles/falcon_install/README.md
> README.md typo fix

- roles/falcon_configure/tasks/configure.yml
- roles/falcon_uninstall/tasks/uninstall.yml
Fixes #310 for now..
Will open a new PR to update/fix Mac OSx support and make these tasks more manage state better.
> Noqa lint on no-changed-when

- changelogs/fragments/mac-updates-318.yml
- roles/falcon_configure/tasks/configure.yml
- roles/falcon_install/tasks/api.yml
- roles/falcon_install/tasks/preinstall.yml
- roles/falcon_uninstall/tasks/uninstall.yml
fixes #312 
This PR introduces changes to the 3 roles to fix and improve support for MacOS.
> Fixes and enhances support for MacOS

- .github/workflows/falcon_install.yml
- molecule/falcon_install_allow_downgrade/converge.yml
- molecule/falcon_install_allow_downgrade/molecule.yml
- molecule/falcon_install_allow_downgrade/prepare.yml
- molecule/falcon_install_allow_downgrade/verify.yml
- roles/falcon_install/README.md
- roles/falcon_install/defaults/main.yml
- roles/falcon_install/tasks/install.yml
Fixes #329 
This PR introduces a new variable that allows users to opt-in to allows package downgrades for Linux Falcon sensor. Tests have also been added.
> Allow downgrading

- .pre-commit-config.yaml
- roles/falcon_configure/meta/main.yml
- roles/falcon_configure/tasks/configure.yml
- roles/falcon_install/meta/main.yml
- roles/falcon_uninstall/meta/main.yml
Fix issues associated with latest ansible-lint updates.
> Update pre-commit and fix ansible-lint issues

- .github/workflows/falcon_configure.yml
- .github/workflows/falcon_install.yml
- .github/workflows/falcon_uninstall.yml
- .github/workflows/win_falcon_configure.yml
- .github/workflows/win_falcon_install.yml
- .github/workflows/win_falcon_uninstall.yml
- molecule/falcon_configure/molecule.yml
- molecule/falcon_install/molecule.yml
- molecule/falcon_install_allow_downgrade/molecule.yml
- molecule/falcon_install_policy/molecule.yml
- molecule/falcon_uninstall/molecule.yml
- molecule/shared/playbooks/win_create.yml
- molecule/win_falcon_configure/molecule.yml
- molecule/win_falcon_install/converge.yml
- molecule/win_falcon_install/molecule.yml
- molecule/win_falcon_install_policy/converge.yml
- molecule/win_falcon_install_policy/molecule.yml
- molecule/win_falcon_uninstall/molecule.yml
- molecule/win_falcon_uninstall/prepare.yml
This PR introduces the use of 2 new variables for further customization and control of jobs.
> Minor molecule updates

- changelogs/fragments/fix-windows-dest-url.yml
- roles/falcon_install/tasks/win_url.yml
> Fix bug with using incorrect temp path for windows

- .devcontainer/requirements.txt
- .pylintrc
- extensions/eda/plugins/event_source/eventstream.py
- galaxy.yml
- meta/extensions.yml
- tox.ini
This PR fixes the Ansible EDA partner requirement linting for certification, to include ruff, darglint, and pylint. Any necessary exclusions have been added.
> Eda partner testing

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/3.3.1.yml
- galaxy.yml
Includes latest eda partner updates
> bump 3.3.1

- README.md
> Update README to reflect proper ansible version support

- changelogs/fragments/fix-become-issue-aid.yml
- roles/falcon_configure/tasks/main.yml
> Fix issue with remove aid not having become clause

- README.md
- plugins/module_utils/falconctl_utils.py
- plugins/modules/falconctl.py
- plugins/modules/falconctl_info.py
Doing some house keeping for devel branch.
> Plugins cleanup linting

- README.md
- plugins/module_utils/common_args.py
- plugins/module_utils/version.py
- plugins/modules/auth.py
- plugins/modules/cid_info.py
- plugins/modules/sensor_update_policy_info.py
Adds cid_info module to help retrieve CID with checksum
Also renames the args_common module to common_args
> Cid info module

- .github/workflows/falcon_configure.yml
- .github/workflows/falcon_install.yml
- .github/workflows/falcon_uninstall.yml
- .github/workflows/win_falcon_configure.yml
- .github/workflows/win_falcon_install.yml
- .github/workflows/win_falcon_uninstall.yml
- molecule/falcon_configure/molecule.yml
- molecule/falcon_configure/prepare.yml
- molecule/falcon_install/converge.yml
- molecule/falcon_install/molecule.yml
- molecule/falcon_install/prepare.yml
- molecule/falcon_install_allow_downgrade/converge.yml
- molecule/falcon_install_allow_downgrade/molecule.yml
- molecule/falcon_install_allow_downgrade/prepare.yml
- molecule/falcon_install_policy/converge.yml
- molecule/falcon_install_policy/molecule.yml
- molecule/falcon_install_policy/prepare.yml
- molecule/falcon_uninstall/molecule.yml
- molecule/falcon_uninstall/prepare.yml
- molecule/win_falcon_configure/molecule.yml
- molecule/win_falcon_configure/prepare.yml
- molecule/win_falcon_install/molecule.yml
- molecule/win_falcon_install_policy/molecule.yml
Updating existing workflows/molecule to support new module changes and doing some minor cleanup.
> Molecule updates devel branch

- roles/falcon_configure/README.md
- roles/falcon_configure/tasks/configure.yml
- roles/falcon_install/README.md
- roles/falcon_install/defaults/main.yml
- roles/falcon_uninstall/README.md
closes #401 
Most of the changes are structured around updating the role README's and some minor changes.
> Prep changes for next v3 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/3.3.2.yml
- changelogs/fragments/fix-become-issue-aid.yml
- changelogs/fragments/remove-host.yml
- galaxy.yml
> Bump v3.3.2

- README.md
- meta/runtime.yml
- roles/falcon_configure/README.md
- roles/falcon_install/README.md
- roles/falcon_uninstall/README.md
> chore: update min ansible-core due to 2.12 EOL

- changelogs/fragments/discover-fix.yml
- plugins/inventory/falcon_discover.py
- plugins/modules/sensor_download_info.py
Fixed an issue with dynamic inventory compose (constructed). Was missing hostname as a param.
Updated some incorrect docs.
> fix(falcon_discover): fixed issue with compose

- changelogs/fix-configure-role.yml
- roles/falcon_configure/tasks/main.yml
> fix(falcon_configure): updates auth task for role

- meta/runtime.yml
This is for certification purposes
> chore: update meta to support 2.14.x

- changelogs/fragments/448-sles-fix.yml
- roles/falcon_install/tasks/preinstall.yml
> fix(falcon_install): ensure proper value for Suse family

- .devcontainer/requirements.txt
- README.md
- requirements.txt
> chore: update falconpy + clean up docs

- .flake8
- .pylintrc
- extensions/eda/plugins/event_source/eventstream.py
- tox.ini
closes #387 
This is inline with what Ansible recommends with their tox.ini file. Also updated flake8/pylint from main branch updates
> V3 lint updates

- .github/workflows/falcon_configure_remove_aid.yml
This workflow will test the changes introduced from #486
> chore: add new gh workflow for testing removing aid

- README.md
- changelogs/fragments/host_ids.yml
- plugins/lookup/host_ids.py
This lookup plugin allows you to fetch a list of host ids based on a search criteria. This is very useful to use for other host modules in the collection. Fixes #502
> feat: new host_ids lookup plugin

- README.md
- changelogs/fragments/host_info.yml
- plugins/modules/host_info.py
Closes #479
This new module provides details for one or more hosts.
> feat: add new host_info module

- README.md
- plugins/lookup/maintenance_token.py
Closes #490
This lookup plugin allows you to fetch a maintenance token for your host, or a bulk token.
> feat: add new lookup plugin to fetch maintenance token

- .pylintrc
- README.md
- changelogs/fragments/fctl-child-cid-info.yml
- plugins/lookup/fctl_child_cids.py
- plugins/modules/fctl_child_cid_info.py
Closes #514 
Introduces a new module to get details for Flight Control child CIDs.
> feat: add new flight control child cid info module

- plugins/modules/fctl_child_cid_info.py
> docs(fctl_child_cid_info): correct group to global

- changelogs/fragments/paginate-kernel-support-info.yml
- plugins/doc_fragments/info.py
- plugins/module_utils/falconpy_utils.py
- plugins/modules/kernel_support_info.py
Fixes #555
This PR adds the ability to handle pagination on behalf of the user for the `kernel_support_info` module.
It also adds a helper function to allow info modules to use the same pagination support.
> feat(kernel_support_info): adds automatic pagination support

- plugins/inventory/falcon_discover.py
- plugins/inventory/falcon_hosts.py
> docs(inventory): add api scopes to dynamic inventories

- README.md
> docs: update README to be inline with Ansible partner guidelines

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/4.7.1.yml
- changelogs/fragments/fix-windows-uninstall-regex.yml
- galaxy.yml
includes windows uninstall hotfix
> Bump 4.7.1

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/599-gpg-key.yml
- galaxy.yml
minor release to get new rpm gpg key out
> chore: bump v4.7.3

- .devcontainer/requirements.txt
Initially we pinned this as there were ssh issues. Need to retest this to see if they have been fixed
> ci: update requirements.txt for ansible-core version
