galaxy.yml
roles/falcon_installation/tasks/api.yml

This PR addresses issue #56 
the `os_version`  comes back as a string
it sometimes contains 1 version ie `8 `for RHEL/CENTOS
sometimes it comes base as multiple versions ie `16/18/20` for ubuntu
to handle this properly have made the change to `contains` from `equalto` in api.yml

changed to `contains` to address #56

---

roles/falcon_installation/tasks/install.yml

Removed redundant code of checking to see if package was already installed prior to installation. Ansible does this by default. Also added the ability to downgrade packages for both DEB and RPM based distros.

Allows downgrading packages a possibility

---

roles/falcon_installation/tasks/api.yml
roles/falcon_installation/tasks/install.yml
roles/falcon_installation/tasks/main.yml
roles/falcon_installation/tasks/preinstall.yml
roles/falcon_installation/tasks/url.yml
roles/falcon_installation/tasks/win_api.yml
roles/falcon_installation/tasks/win_install.yml
roles/falcon_uninstall/tasks/uninstall.yml
roles/falcon_uninstall/tasks/win_uninstall.yml
tests/ansible-lint.conf

- Recommended by Ansible to avoid using external collections that might have the same name

Use FQCN instead of short names for modules

---

roles/falcon_installation/README.md
roles/falcon_installation/defaults/main.yml
roles/falcon_installation/tasks/api.yml
roles/falcon_installation/tasks/preinstall.yml
roles/falcon_installation/tasks/win_api.yml
roles/falcon_uninstall/README.md

Fixes #61 
- Added more examples in the README
- Added the ability to specify a sensor update policy name to manage what version of the falcon sensor gets installed
- minor fixes to README and preinstall.yml

Gives the ability to specify a sensor update policy

---

roles/falcon_installation/tasks/install.yml

Utilized the `omit` filter to help reduce the package installation to just one task.

Cleaned up the way we handle package installs on Linux

---

.github/workflows/falcon_installation.yml
molecule/falcon_installation/cleanup.yml
molecule/falcon_installation/molecule.yml

This PR allows the use of the `pull_request_target`, enabling us to run the Molecule testing using the GH secrets. I've also added the changes to Molecule to allow testing of the uninstall_role inside the installation_role

Enable pull_request_target + molecule changes

---

plugins/module_utils/falconctl_utils.py
plugins/modules/falconctl.py
plugins/modules/falconctl_info.py

This is a complete Ansible Module for replicating the falconctl cli behavior as best as possible within the current cli limitations. This module consists of 3 parts:
1. `falconctl_utils.py` is a module_utils file that has shared functions to be used across the other falcon modules
2. `falconctl.py` is the main module used to replicate falconctl cli behavior*
3. `falconctl_info.py` is an info module used to get values from the falconctl. You can pass either a list of interested values, or you can simply return all values associated with the GET operation in the cli.

Falconctl Ansible module support (WIP)

---

roles/falcon_installation/tasks/install.yml
roles/falcon_installation/tasks/preinstall.yml
roles/falcon_installation/tasks/win_install.yml

The default behavior for tempfile is to not be idempotent, especially when created and removed. This change ignores the changes, allowing it to appear "idempotent".

Added changed_when clause to support idempotency

---

galaxy.yml

updating the windows dependency to the earliest version found on Automation Hub

updating windows dependency to be at certified minimum

---

molecule/falcon_configure/converge.yml
molecule/falcon_configure/verify.yml
plugins/modules/falconctl.py
roles/falcon_configure/README.md
roles/falcon_configure/defaults/main.yml
roles/falcon_configure/handlers/main.yml
roles/falcon_configure/tasks/configure.yml

closes #110 
This PR fixes:
- Removal of `--metadata-query` falconctl options (not supported at this time)
- Adds better test support for molecule verify stage
- Fixes bug in `add_args` function dealing with empty strings which are useful and valid for delete operations
- Fixed bug with `--message-log` needing to be lowercased to match get option value
- Added `--billing` param validation
- Added functionality/error-handling around the `falcon_configure` role handler. The falcon-sensor can't restart when no CID is attached.

Merged falcon_configure options tasks + minor fixes

---

README.md
molecule/falcon_configure/verify.yml
roles/falcon_configure/README.md
roles/falcon_configure/defaults/main.yml
roles/falcon_configure/tasks/api.yml
roles/falcon_configure/tasks/main.yml
roles/falcon_configure/vars/main.yml
tests/test.yml

closes #113 
- Adds the ability to autodetect CID if API credentials are known. This is something that was originally in falcon_installation.
- Added tests in Molecule
- Updated our collections tests to showcase usage and make it actually workable

Adding autodetect cid feature to configure role

---

.github/workflows/ansible-test.yml

Add matrix strategy for python versions. This prevents issues with using the docker version that doesn't have access to the falconctl bin

updated workflow for ansible-test

---

roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/win_api.yml

- Redirects are no longer working and the payload is never returned with the oauth token. This is a janky fix that 
authenticates to the API twice to get the token and csregion in separate tasks

Add duplicate API task to authenticate to cloud

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
.github/workflows/win_falcon_configure.yml
.github/workflows/win_falcon_install.yml
.github/workflows/win_falcon_uninstall.yml
README.md

- Updated README to remove Window build status due to instability
- Renamed the `name:` for the workflows to be short and concise. Makes it easier to view in Actions as well as in badges.

Renamed workflows, removed windows build due to flakiness

---

.github/workflows/win_falcon_configure.yml
.github/workflows/win_falcon_install.yml
.github/workflows/win_falcon_uninstall.yml

This allows us to still test Windows, but not be concerned with the current flakiness surrounding the molecule testing on Windows.

added continue-on-error to molecule run

---

galaxy.yml
roles/falcon_configure/handlers/main.yml

Fixed an issue where the restart sensor task was failing because it wasn't assuming elevated privileges. We didn't catch this in molecule since the containers use root by default.

Added issue with handler not running with sudo

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml

There is an issue with CentOS8 finally getting EOL'd. This replaces centos8 with rockylinux8. I've submitted an upstream [PR](https://github.com/geerlingguy/docker-centos8-ansible/issues/19) to fix the current issue which is to point to the new vaulted mirrors for packages, but this is an archive, and will not be updated. 
I've also submitted an [issue](https://github.com/geerlingguy/docker-centos8-ansible/issues/20) to see if he can create a new repo for CentOS Stream, as this is the way forward.

Fixes issue with EOL Centos8 mirrors

---

roles/falcon_configure/tasks/api.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/win_api.yml

Fixes #146 
This implements Ansible's no_log feature to essentially hide any output that could be logged to expose api creds. As the OP of #146 stated, there is an open issue for the uri module to add a header_secret, but until then, this is the only way to mask it.

Added no_log to API tasks to prevent sensitive output

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
roles/falcon_configure/README.md
roles/falcon_configure/defaults/main.yml
roles/falcon_configure/tasks/api.yml
roles/falcon_install/README.md
roles/falcon_install/defaults/main.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/preinstall.yml
roles/falcon_install/tasks/win_api.yml

Closes #148
- Adds new sensor-update-kernels API functionality. This gives us the ability to check if the kernel on Linux is compatible, and if so, is the sensor-version being used compatible with the kernel.
- Currently this will issue a failure warning, but will be ignored. This can be useful to see if the deployment will most likely result in the falcon sensor being in RFM mode due to kernel compatibility issues.
- Added a new variable: `falcon_api_enable_no_log` to manage whether or not a user might want to expose their API credentials + authorization token during a run. It may be useful for troubleshooting purposes, otherwise we think it's a good idea to leave this at the default value.
- Added a new variable: `falcon_skip_kernel_compat_check` to manage whether or not a user would …

Added new api feature + variablized no_log option

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
.github/workflows/win_falcon_configure.yml
.github/workflows/win_falcon_install.yml
.github/workflows/win_falcon_uninstall.yml

Slim down the number of OS to run for our CI molecule testing. A lot of them are redundant and provide no additional insight.

Slimming down OS's for CI

---

.ansible-lint
galaxy.yml
roles/falcon_install/tasks/api.yml

on RHEL - there was an issue with distro_version not being correct according to the kernel version. This now filters based on vendor and kernel version to get supported sensors.

Due to limitation in api, removed distro_version filter

---

roles/falcon_configure/README.md
roles/falcon_install/README.md

Adding documentation better explaining the required API scopes needed for Roles that utilize API calls. Those roles are currently the:
- falcon_install
- falcon_configure
Might help with issues such as #154

Updating role docs for api scopes

---

roles/falcon_uninstall/tasks/uninstall.yml

There was an issue when running the uninstall_role would not completely purge the falcon-sensor package from debian based systems.

Adding purge for apt-based uninstalls

---

.github/workflows/ansible-test.yml
galaxy.yml

- Removes .devcontainer from being included in the ansible-collection build, which prevents shellcheck issues associated with files in there
- Updates ansible-test workflow to support new python 3.10.4 version.

Ignore .devcontainer from collection build

---

.github/workflows/release.yml

This was removed in #162 
@redhatrises I believe this was accidental and was not the cause for the failing of the GH release upload right?

re-added ansible galaxy upload command

---

galaxy.yml
roles/falcon_install/tasks/preinstall.yml

fixes #172 
- Bump'd version
- Fixed when clause to only target legacy amzn1 os

Updated when clause to ensure task only on legacy amzn os

---

.github/workflows/aap-refresh.yml

Based on AAP documentation, run the following command in order to keep the offline token used for AAP uploads updated. This will ensure we don't run into any issues when cutting a new release outside of the 30 day window, as well as give us the flexibility to update our token key as needed.

New workflow to keep aap offline token refreshed

---

roles/falcon_configure/meta/main.yml
roles/falcon_configure/tasks/configure.yml
roles/falcon_configure/tasks/win_configure.yml
roles/falcon_install/meta/main.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/install.yml
roles/falcon_install/tasks/preinstall.yml
roles/falcon_install/tasks/url.yml
roles/falcon_install/tasks/win_api.yml
roles/falcon_install/tasks/win_install.yml
roles/falcon_uninstall/meta/main.yml
roles/falcon_uninstall/tasks/main.yml
roles/falcon_uninstall/tasks/uninstall.yml
roles/falcon_uninstall/tasks/win_uninstall.yml

From the latest ansible-lint changes, we were flagged with a few items. This PR addresses those items by commit.
**NOTE:** There is an existing [issue](https://github.com/ansible/schemas/issues/298) for one of the items that was flagged in which we cannot use a variable for certain tasks parameters (in our case, the `delay` param). Will wait a few days or so to see if it gets addressed.

184 fix ansible lint issues

---

roles/falcon_install/tasks/api.yml

Fixes #186 
Adds support for the `ztl_supported_sensor_versions` resource field in order to check against supported ZTL versions.

Add ztl support for kernel compat checks

---

galaxy.yml
roles/falcon_install/tasks/preinstall.yml

This fixes an issue with Amazon Linux reporting the wrong falcon_os_vendor value since it's os_family is RedHat.

Fix amazon os family error

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
.github/workflows/win_falcon_configure.yml
.github/workflows/win_falcon_install.yml
.github/workflows/win_falcon_uninstall.yml

During pip install - this is the message received as to why Ansible does not get installed:
```shell
WARNING: molecule 4.0.0 does not provide the extra 'ansible'
```
This PR add ansible to pip list

Molecule seems to no longer install ansible according to pip

---

roles/falcon_install/tasks/win_api.yml

Fixes #201 
The duplicate api call to authenticate task was causing the already registered `falcon_api_oauth2_token` variable to be wiped when skipped over. This fix makes it inline with how we do it on the *nix side.

Fixed issue with duplicate api-call overwriting registerd var

---

molecule/falcon_configure/converge.yml
roles/falcon_configure/tasks/api.yml
roles/falcon_install/tasks/win_api.yml

closes #217 
* Fixes missing redirect follows in falcon_configure role and win_api.yml task in falcon_install role
* Updates molecule falcon_configure testing to ensure this is easier to test locally

Redirects should have been added to other role/tasks

---

.github/workflows/pages.yml

This PR introduces the permissions needed to push content to the gh-pages branch via the workflow

Pages WF needs permission to push to branch

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml

Allow a way to retry molecule failed jobs - that are usually caused by some race condition or some quirk. Manually re-running a failed job usually fixes the issue, so this is an attempt to do it programatically.

Adding retries to reflect better test status

---

changelogs/fragments/fix-incorrect-arm64-assumptions.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/preinstall.yml

fixes #244 
This fixes an error with our API not having an existing architecture field to ensure that when we ask for the list of available sensors to download, we get the one for the existing architecture.

Fix incorrect arm64 assumptions on api call

---

.devcontainer/devcontainer.json
.devcontainer/requirements.txt
.pre-commit-config.yaml

* Add flake8 and pylint to pre_commit
* Update pre_commit install to also initialize the hook environments
* Moved ansible extension down the list since it depends on the python extension
* Add autopep8

add python linting to pre_commit

---

changelogs/fragments/add-local-file-install-method.yml
roles/falcon_install/README.md
roles/falcon_install/defaults/main.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/file.yml
roles/falcon_install/tasks/install.yml
roles/falcon_install/tasks/main.yml
roles/falcon_install/tasks/preinstall.yml
roles/falcon_install/tasks/win_api.yml
roles/falcon_install/tasks/win_install.yml

Allows to install from a file local to orchestrator

add file install method

---

changelogs/fragments/fix-failing-aid-master-prep.yml
molecule/falcon_configure/verify.yml
roles/falcon_configure/handlers/main.yml
roles/falcon_configure/tasks/configure.yml
roles/falcon_configure/tasks/main.yml
roles/falcon_configure/tasks/remove_aid.yml

closes #254 
When trying to remove the aid to prep for master image/clone, there was an issue with embedding the `falcon_remove_aid` functionality into the configure task. This was causing this task to always run:
```yaml
- name: CrowdStrike Falcon | Configure Falcon Sensor Options (Linux)
```
By extracting the actual tasks needed to remove the aid - and prevent the service from being bounced, a few changes were introduced to this PR:
- No longer need a handler for this role. The sensor should be bounced immediately after registering changes. This allows users to run a play where they add the CID and other config items, then want to remove the aid to prep an image. Example playbook:
```yaml
---
- name: Configure and prep falcon
hosts: all
tasks:
- name: Set CID and tags …
```

Fixed issue with removing aid for master image prep in falcon_configure

---

changelogs/fragments/fix-falcon-configure-var-issue.yaml
roles/falcon_configure/README.md
roles/falcon_configure/defaults/main.yml
roles/falcon_configure/tasks/api.yml
roles/falcon_configure/vars/main.yml

closes #257 
This issue stemmed from the `falcon_cloud` variable in the `falcon_configure` role being technically in the wrong place. However, this PR fixes that issue, as well as brings the API authentication functionality in the `falcon_install` role in line with this role.

Fix falcon_cloud in falcon_configure role functionality

---

.devcontainer/library-scripts/docker-in-docker-debian.sh
roles/falcon_configure/tasks/api.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/win_api.yml

fixes #260 
In response to issue #260 - The idea here is to utilize the run_once ansible playbook keyword to prevent multiple API calls on tasks where it makes sense, such as:
- Authentication to API
- Sensor Update Policy
What run_once is:
> Boolean that will bypass the host loop, forcing the task to attempt to execute on the first host available and afterwards apply any results and facts to all active hosts in the same batch.
So basically this will only run the task on one host, and use that output for the other hosts (think bearer token or sensor update policy sensor version)
Also in this PR is updates to new Ansible-lint rules and pre-commit changes.

Implement run once feature

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
.github/workflows/win_falcon_configure.yml
.github/workflows/win_falcon_install.yml
.github/workflows/win_falcon_uninstall.yml
roles/falcon_install/tasks/win_install.yml

This PR addresses:
- The Linux CI jobs were failing whenever a job was launched on ubuntu 22.04 runner. GH is in the middle of transitioning the `ubuntu-latest` tag from 20.04 to 22.04 so that is why this is a random failing event. We will use 20.04 until we figure out why 22.04 does not work the same way.
- Fixed an Ansible lint issue for the Windows jobs. Updated the Windows workflows to fail instead of continuing on error.

Update workflows due to runner issues

---

roles/falcon_configure/tasks/main.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/auth.yml
roles/falcon_install/tasks/main.yml
roles/falcon_install/tasks/win_api.yml

closes #271 #272 
This PR introduces the following changes:
- falcon_install
- Create new `auth.yml` file to handle api authentication, irregardless of operating system
- Add new include_task: auth.yml to both API blocks 
- falcon_configure
- Replace `api.yml` task by including the new `auth.yml` from the falcon_install role

Refactored API authentication for better use-ability

---

roles/falcon_install/tasks/api.yml

Fixes https://github.com/CrowdStrike/ansible_collection_falcon/issues/275
This fixes an error with our API not having an existing architecture field to ensure that when we ask for the list of available sensors to download, we get the one for the existing architecture.

add arch filter in API URL

---

roles/falcon_install/tasks/preinstall.yml

Fixes #283 
Windows/Mac currently do not differentiate themselves with os architecture in the API queries. This PR moves the logic to apply only to Linux systems.

Moves falcon_os_arch to Linux only

---

CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml

Includes fix for non-linux systems for determining arch for sensor queries.

Bump version to 3.2.26

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
.github/workflows/win_falcon_configure.yml
.github/workflows/win_falcon_install.yml
.github/workflows/win_falcon_uninstall.yml
molecule/falcon_configure/cleanup.yml
molecule/falcon_configure/converge.yml
molecule/falcon_configure/molecule.yml
molecule/falcon_configure/prepare.yml
molecule/falcon_configure/verify.yml
molecule/falcon_install/cleanup.yml
molecule/falcon_install/converge.yml
molecule/falcon_install/molecule.yml
molecule/falcon_install/prepare.yml
molecule/falcon_install/verify.yml
molecule/falcon_uninstall/converge.yml
molecule/falcon_uninstall/prepare.yml
molecule/falcon_uninstall/verify.yml
molecule/win_falcon_configure/cleanup.yml
molecule/win_falcon_configure/molecule.yml
molecule/win_falcon_configure/prepare.yml
molecule/win_falcon_install/cleanup.yml
molecule/win_falcon_install/converge.yml
molecule/win_falcon_install/molecule.yml
molecule/win_falcon_uninstall/molecule.yml
molecule/win_falcon_uninstall/prepare.yml
roles/falcon_install/tasks/auth.yml

This PR introduces changes associated with fixing issues causing our CI jobs to fail. Some of these changes are in support of the new backend kernel option which makes `aid` acquisition trickier from a CI perspective. A follow up PR #287 for adding changes to support that option will follow.

Changes to fix broken CI

---

roles/falcon_configure/tests/test.yml
roles/falcon_uninstall/tests/test.yml
tests/test.yml

Fixes the following Ansible Lint errors:
```terminal
name[play]: All plays should be named.
roles/falcon_configure/tests/test.yml:2
name[play]: All plays should be named.
roles/falcon_uninstall/tests/test.yml:2
name[play]: All plays should be named.
tests/test.yml:2
You can skip specific rules or tags by adding them to your configuration file:
warn_list:  # or 'skip_list' to silence them completely
- name[play]  # Rule for checking task and play names.
Rule Violation Summary
count tag        profile rule associated tags
3 name[play] basic   idiom
```

Ensure plays are named - per ansible-lint

---

molecule/falcon_configure/prepare.yml
molecule/falcon_install/prepare.yml
molecule/falcon_install_policy/prepare.yml
molecule/falcon_uninstall/prepare.yml
roles/falcon_configure/tasks/configure.yml
roles/falcon_configure/tasks/main.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/auth.yml
roles/falcon_install/tasks/install.yml
roles/falcon_install/tasks/main.yml
roles/falcon_install/tasks/preinstall.yml
roles/falcon_install/tasks/win_install.yml
roles/falcon_uninstall/tasks/main.yml
roles/falcon_uninstall/tasks/uninstall.yml
roles/falcon_uninstall/tasks/win_uninstall.yml

Closes #298 
This PR provides a more compatible way of using ansible facts. By default, as of Ansible 2.5 they have allowed facts to be used with a top-level naming schema of: ansible_<facts>
Down the road, this will eventually be shifted to use the ansible_facts dictionary to prevent collisions with other modules that may use ansible_* naming conventions.

Update ansible facts to use dictionary as opposed to magic name

---

roles/falcon_install/tasks/auth.yml

This PR is trying to address an Ansible issue from #300 and issues associated to localhost delegation. Idea is to revert back to using `delegate_to: localhost` to prevent having to use omit keyword, and ensure the task(s) don't need to privilege (sudo). 
Hopefully fixed #305

Fix delegate_to and potential omit bug

---

roles/falcon_configure/tasks/main.yml
roles/falcon_install/tasks/auth.yml
roles/falcon_install/tasks/main.yml
roles/falcon_install/tasks/win_auth.yml

Originally the idea was to refactor all auth calls to localhost or nix* guests to take advantage of the more mature builtin.uri module. However, after some Ansible bugs in 2.12 were exposed around omitting args + some additional headaches around dealing with delegating to localhost when targeting Windows, this PR breaks auth apart for it's respective OS. For the Windows side, it also now handles following redirects when a 308 is encountered.

Extracts windows auth into own file for better support

---

changelogs/fragments/run-once-320.yml
roles/falcon_install/README.md
roles/falcon_install/defaults/main.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/auth.yml
roles/falcon_install/tasks/win_api.yml

Closes #319 
This PR introduces the ability to allow a user to skip the `run_once` options on the API calls. Currently, this is enabled with no ways of overriding it.

Adding variable to control run_once API option

---

changelogs/fragments/fix-decrement-sorting.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/win_api.yml

Fixes #323 
This PR adds sorting to the sensor installer query to ensure we get back the correct ordering in order to use the version decrement correctly.

Add sort|desc to os_version in sensor query

---

changelogs/fragments/fix-kernel-compat-query.yml
roles/falcon_install/tasks/api.yml

Fixes #331 
This PR addresses an issue with the kernel compat API call results. Results now include architectural differences so we have to account for these with filters. 
> This was accomplished by adding the `architecture: "ansible_facts['architecture']"` filter
Unfortunately, the fql filter to check if some string is in distro_version does not work as intended. As a workaround, I created a new fact that searches for the distro major version in the resources[*].distro_version field.
> This was accomplished by using the selectattr filter: `selectattr('distro_version', 'search', ansible_facts['distribution_major_version'])`

Add arch to kernel compat query + add new json filter for proper subset

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
molecule/win_falcon_configure/molecule.yml
molecule/win_falcon_install/molecule.yml
molecule/win_falcon_install_policy/molecule.yml
molecule/win_falcon_uninstall/molecule.yml

Molecule issues with docker python dependencies and vagrant box versions

Fix molecule issues

---

roles/falcon_install/tasks/install.yml

Fixes #343 
This PR fixes an issue when the zypper package manager module is used, allow_downgrade is not a valid option. Instead, it uses oldpackage to allow downgrading.

Fix downgrade issue with SUSE/zypper

---

.github/workflows/falcon_install.yml
molecule/falcon_install_allow_downgrade/converge.yml

Due to the recent addition of Amazon 2023 support - there is only one current version of the sensor available, so that was throwing off the policy and downgrade ci.
- Added matrix exclusion for falcon_install_allow_downgrade role on Amazon-2023 until more sensor versions are available.
- Changed falcon_sensor_version_decrement from 2 to 1 in falcon_install_allow_downgrade converge configuration.

fix: Update matrix exclusion and falcon sensor version decrement

---

.ansible-lint

This really is not a big deal, plus we can revisit this when we move towards v4.

Skipping role_prefix var naming rule

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
.github/workflows/win_falcon_install.yml
.github/workflows/win_falcon_uninstall.yml

Not sure why I never had Amazon Linux 2 in CI, but adding it here.
Also staggering CI scheduled jobs to see if that helps with existing CI errors and to prevent any resource contention.

Add amazon linux 2 to ci + stagger schedule

---

changelogs/changelog.yaml
changelogs/fragments/url_ability_for_windows.yml
roles/falcon_install/tasks/main.yml
roles/falcon_install/tasks/win_url.yml

hello,
Sorry for the spam here... Reopened a new one due to a mistake that I did.
This PR is a clone of this one: https://github.com/CrowdStrike/ansible_collection_falcon/pull/362

falcon_install - add the ability to install from an url link for windows

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
changelogs/fragments/remove-kernel-compat.yml
roles/falcon_install/README.md
roles/falcon_install/defaults/main.yml
roles/falcon_install/tasks/api.yml

Closes #356 
This PR removes the need for the `falcon_skip_kernel_compat_check` kernel compatibility step since the falcon sensor has introduced eBPF support. The reasoning to remove this is as follows:
- None of our other tools provide this capability
- One less API call to be dependent on in terms of reliable information
- Handling edge cases like RHEL 8, where a kernel that is less than the 5.8 but has a compatible ebpf backport would be difficult to track w/o an API to check.
This should be a minor change - even if you are still using the `falcon_skip_kernel_compat_check` variable, it won't be used as there is no call to it within the role.

Removed kernel compat due to prevelance of ebpf support

---

changelogs/fragments/url_ability_for_windows.yml
roles/falcon_install/tasks/win_url.yml

The temp file path will be where the file is downloaded to. This does not impact the name. 
If you have a url: `http://example.com/path/to/sensor.exe` 
Then it will be `falcon_windows_tmp_dir.path/sensor.exe` which might look something like this: `C:\\Windows\\Temp\\ansible.1jm0zgju.podfalcon\\sensor.exe`

dest should follow same convention as linux

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/3.3.0.yml
changelogs/fragments/eda.yml
changelogs/fragments/fix-windows-dest-url.yml
galaxy.yml

This release bumps to 3.3.0 due to the addition of the EDA event_source plugin.

Bump 3.3.0

---

changelogs/fragments/remove-host.yml
molecule/falcon_uninstall/converge.yml
molecule/falcon_uninstall/prepare.yml
molecule/win_falcon_uninstall/converge.yml
molecule/win_falcon_uninstall/verify.yml
roles/falcon_uninstall/README.md
roles/falcon_uninstall/defaults/main.yml
roles/falcon_uninstall/tasks/hide_host.yml
roles/falcon_uninstall/tasks/main.yml
roles/falcon_uninstall/tasks/pretasks.yml
roles/falcon_uninstall/tasks/preuninstall.yml
roles/falcon_uninstall/tasks/remove_host_pretasks.yml
roles/falcon_uninstall/tasks/win_uninstall.yml
roles/falcon_uninstall/vars/main.yml

Fixes #380 
This PR adds support for Removing/Hiding a host from the Falcon Console when uninstalled. This is a good way to help keep your host management view clear of clutter.
Some notable changes:
- **API Integration**: Because this is an api call, we now bring in the same API authentication from the other roles. 
- **Documentation updates**: `falcon_remove_host` controls whether you want to hide/remove host. Default is `false`
- **Uninstall Logic Enhancements**: Better way to check for existing sensors to make it easier to ensure certain tasks are run when needed.
- Windows uninstall has an additional check to ensure the playbook waits for the sensor to be uninstalled before proceeding.

Add remove/hide host ability for uninstall

---

README.md
plugins/doc_fragments/credentials.py
plugins/doc_fragments/info.py
plugins/modules/host_hide.py
roles/falcon_configure/README.md
roles/falcon_configure/tasks/configure.yml
roles/falcon_install/README.md
roles/falcon_uninstall/README.md
roles/falcon_uninstall/defaults/main.yml
roles/falcon_uninstall/tasks/hide_host.yml
roles/falcon_uninstall/tasks/main.yml

This PR introduces the `host_hide` module. This is the final API call to complete the roles. 
This also updates all the README's to ensure they all follow the same formatting. A few minor fixes here and there as well.

Host hide module + doc updates

---

README.md
plugins/inventory/falcon_discover.py

This PR introduces a new dynamic inventory for the (currently) Discover service collection. This allows us to get details on managed/unmanaged hosts, as well as cloud information for those hosts that live in the cloud and much more. This inventory supports the standard Ansible inventory features such as caching and constructing group/host vars.

discover dynamic inventory

---

README.md
changelogs/fragments/host_contain.yml
plugins/modules/host_contain.py

The PR introduces the host_contain module to manage the network containment state of a Falcon host.
Also fixes #410

Host contain module

---

changelogs/fragments/fix-eu-mapping.yml
plugins/module_utils/falconpy_utils.py

The url for the eu-1 cloud seems to be wrong

fix eu-1 url

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
.github/workflows/linting.yml
.github/workflows/win_falcon_configure.yml
.github/workflows/win_falcon_install.yml
.github/workflows/win_falcon_uninstall.yml

Github actions was failing due to the version of python that was being used (latest: 3.12). We currently only support up to 3.11 so pinning the actions to 3.11 fixed those issues.

chore: workflow py versions should not pass supported

---

.github/workflows/ansible-lint.yml
.pre-commit-config.yaml
plugins/modules/host_hide.py

For certification, ensure we are passing on ansible-lint 6.22.x+

Update ansible lint

---

README.md
galaxy.yml

can't find any good examples where the ansible.eda collection is a dependency for a collection that authors an event_source plugin for eda. This was affecting creation of DE and EE for AAP.

chore: remove dep on eda collection and update core support

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml

CI is failing because `suse-sles-15-sp4-v????????-hvm*` is no longer valid.

chore: update sles ec2 image for workflows

---

changelogs/fragments/get_bin_path.yml
plugins/module_utils/falconctl_utils.py

The parameter `required` in process.get_bin_path is useless.
Remove and update the usage of get_bin_path in inventory and lookup
plugins.
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
- Bugfix Pull Request

Remove superfluous param from get_bin_path

---

molecule/falcon_configure/converge.yml
molecule/falcon_configure/verify.yml
molecule/falcon_uninstall/prepare.yml
molecule/win_falcon_configure/prepare.yml
molecule/win_falcon_install/converge.yml
molecule/win_falcon_install_policy/converge.yml
molecule/win_falcon_uninstall/prepare.yml

Fixes #424
This PR ensures that sensors installed during ci/cd runs have the same grouping tags applied. This will make it easier to clean up on the console side.

chore: ensure tags on cicd hosts to allow cleanup on console

---

.flake8
.pylintrc
plugins/inventory/falcon_discover.py
plugins/modules/sensor_download.py

chore: update python linting for modules

---

molecule/falcon_configure/converge.yml
molecule/falcon_configure/verify.yml

The message_log option is no longer valid for newer versions of the sensor.

chore: update falcon-configure molecule

---

molecule/falcon_configure/verify.yml
plugins/modules/falconctl.py
roles/falcon_configure/README.md

Affected roles:
- crowdstrike.falcon.falcon_configure
Affected modules:
- falconctl
All the documentation tells you to configure proxy with falcon_aph/aph with protocol included.
```
falcon_aph: "http://{{ proxy__host }}"
```
However if you do that you will get the following
```
CrowdStrike(4): Connect: Unable to resolve http://<Proxy FQDN retracted>, getaddrinfo returned -2
```
To get proxy working you need to use following.
```
falcon_aph: "{{ proxy__host }}"
```
And the connection will work with proxy
```
CrowdStrike(4): trying to connect to <Proxy FQDN retracted>:8080
CrowdStrike(4): ProxyConnect: Connected successfully to "<retracted CS server name>:443" via proxy "<Proxy FQDN retracted>:8080" 
```
This pull request aims to fix the documentation to reflect reality.
*used incorrect …

Fix examples regarding falcon_aph/aph

---

README.md
changelogs/fragments/falcon_hosts.yml
plugins/README.md
plugins/inventory/falcon_hosts.py

This plugin will query our Falcon Hosts API to retrieve all the details associated to the requested filter query.
Closes #458

feat: add new falcon hosts dynamic inventory plugin

---

README.md
SUPPORT.md
roles/falcon_configure/README.md
roles/falcon_install/README.md

Closes #471
Make it clearer that the install role for *nix only installs the sensor. You still need to run the configure role to assign a cid and perform any other configurations before starting.
Also adds our support statement doc

docs: update role docs to be more expressive of what they do per os

---

changelogs/fragments/host_hide_update.yml
plugins/modules/host_hide.py

Fixes: #465 
This commit will allow a user to not have to worry about a) knowing there is a 100 max host limit per API call and b) having to batch chunks in Ansible to pass into the module.

fix(host_hide): allow api limit to be managed in module seamlessly

---

changelogs/fragments/pr-474.yml
plugins/inventory/falcon_hosts.py

Hi,
I suggest this imporovement in order to be able to do some "post-processing" in inventory name. 
In my use case, the vm names are uppercase and the inventory_hostname variable for ansible inventory entries have to be lowercase.
This can be accomplished by:
```YAML
hostnames:
- hostname | lower
```
The actual logic can be achieved by (I don't modified that part)
```YAML
hostnames:
- hostname
- ip_address
```
Let me know,
Bye

Support for hostname templating

---

plugins/inventory/falcon_hosts.py

Hello,
With this PR, I suggest to add the Jinja2 templating support in parameters:
- `client_id`
- `client_secret`
- `member_cid`
`cloud` parameter also could be supported but if you use a Jinja template, the choice validation fails.
Let me know.
Bye

Parameter templating

---

changelogs/fragments/add-file-ops-sensor-download.yml
plugins/modules/sensor_download.py

Fixes #481
This PR introduces the built-in files AnsibleModule helper features to manage file operations such as mode, owner, group, etc.

fix(sensor_download): add file operation support to module

---

roles/falcon_install/README.md
roles/falcon_install/defaults/main.yml
roles/falcon_install/tasks/api.yml

This PR adds the ability to take advantage of passing in mode/owner/group permissions to the sensor download task that were introduced by #485

fix(falcon_install): add ability to use file ownership changes from sensor_download module

---

galaxy.yml
meta/runtime.yml

Fixes #508 
Updating Ansible core requirements due to certification requirements for EOS to AAP 2.3.

Minor updates for 4.4.0 prep

---

README.md
changelogs/fragments/fctl-child-cids.yml
plugins/lookup/fctl_child_cids.py

This new lookup plugin allows Falcon Flight Control (MSSP) users to fetch the children CIDs in their environment. Will be useful to pass into future Flight Control modules, such as getting details about child CIDs.

feat: add new flight control child cid ids lookup filter plugin

---

plugins/modules/sensor_download_info.py

To maintain backwards compatability with FalconPy, we take advantage of the override feature that allows us to use the new sensors/combined/installers/v2 endpoint. This means we can now pass in architectures as a filter.
This also updates the limit to ensure users know the default limit is set to 100.
Closes #488

fix(sensor_download_info): use v2 override for new endpoint

---

changelogs/fragments/v2-sensor-installers.yml
plugins/modules/sensor_download_info.py
roles/falcon_install/vars/main.yml

Closes #489 
This PR updates the `falcon_install` role to take advantage of the new #520 V2 API endpoint updates that allows us to query an architecture now.
Instead of doing the following to only get x86_64 installers:
```yaml
x86_64: "+os_version:!~'arm64'+os_version:!~'zLinux'"
```
We can do this:
```yaml
x86_64: "+architectures:'x86_64'"
```

fix(falcon_install): pass in the appropriate filter for architecture

---

molecule/falcon_uninstall/converge.yml
roles/falcon_uninstall/tasks/main.yml

Fixes #527
The `main.yml` tasks was missing the become clause for the remove host pretasks.
Also fixes the molecule job that would have caught this if it was configured correctly 🤦🏼‍♂️

fix(falcon_uninstall): added missing become clause to pretask

---

changelogs/fragments/uninstall-become.yml
roles/falcon_uninstall/tasks/main.yml
roles/falcon_uninstall/tasks/remove_host_pretasks.yml

Fixes #531 
After the last change in PR#529, this caused an issue obviously for Windows since become method and user were incorrect. This PR makes the become clauses inline with the appropriate blocks.

fix(falcon_uninstall): configure become properly for remove_host_pretask.yml

---

.github/workflows/falcon_configure.yml
.github/workflows/falcon_configure_remove_aid.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml

Centos 7 is EOS so CI jobs fail due to no more repositories available/supported to install applications.

ci: remove centos-7 from molecule testing

---

.github/workflows/falcon_configure_remove_aid.yml
changelogs/fragments/master-image-update.yml
molecule/falcon_configure_remove_aid/converge.yml
molecule/falcon_configure_remove_aid/molecule.yml
molecule/falcon_configure_remove_aid/verify.yml
plugins/module_utils/falconctl_utils.py
plugins/modules/falconctl.py
plugins/modules/falconctl_info.py
roles/falcon_configure/defaults/main.yml
roles/falcon_configure/tasks/configure.yml
roles/falcon_configure/tasks/remove_aid.yml

Fixes #534 
This pull request introduces enhancements and modifications to the Falcon configuration role and molecule testing workflows. 
Key changes include:
- The ability to ensure master images using provisioning tokens set the token after removing the AID based on discussions internally and in #534. 
- Module updates that allows for querying provisioning-token
- Updated molecule test validations to ensure a more thorough master image test

Master image updates

---

changelogs/fragments/duplicate_hosts.yml
plugins/inventory/falcon_discover.py

Fixes #550
This PR adds a new option `allow_duplicates` that will allow the user to display all hosts with the same hostname, differentiated by Asset ID from the Discover API.
**Example:**
You have the following hosts in your environment:
- example-host1
- example-host1
If you set `allow_duplicates: true` then you will see:
- example-host1
- example-host1_fkjlajksdlfjalsdjflkjlasdjflkj_jsdljkfalkjsdlfkja

feat(falcon_discover): allow duplicate hostnames to be listed

---

changelogs/fragments/eda-updates.yml
docs/crowdstrike.falcon.eventstream.md
extensions/eda/plugins/event_source/eventstream.py
tox.ini

Fixes #526 
Fixes #549 
This option is mutually exclusive with offset, and if selected, will allow the event stream to always start from the latest event. This is useful for not having to manage the offset.
This PR also fixes some issues with handling timeout due to refresh interval.

feat(eda): add ability to start stream from the latest event

---

extensions/eda/plugins/event_source/eventstream.py

since offset was of type int, it failed trying to convert `NoneType` to an integer when it was not set by default. Using the Optional[int] allows us to handle this situation to maintain our optional use of offset.

fix(eda): make offset optional for nonetype

---

changelogs/fragments/info-updates.yml
plugins/module_utils/falconpy_utils.py
plugins/modules/kernel_support_info.py
plugins/modules/sensor_download_info.py
plugins/modules/sensor_update_policy_info.py

Closes #556
Limits are not consistent within our APIs to offer them modularly. Instead, you can use native Ansible to further refine and limit the info modules as needed.

feat(info modules): enhance pagination and remove limits

---

changelogs/fragments/toggle-win-become.yml
roles/falcon_configure/README.md
roles/falcon_configure/defaults/main.yml
roles/falcon_configure/tasks/main.yml
roles/falcon_install/README.md
roles/falcon_install/defaults/main.yml
roles/falcon_install/tasks/main.yml
roles/falcon_uninstall/README.md
roles/falcon_uninstall/defaults/main.yml
roles/falcon_uninstall/tasks/main.yml
roles/falcon_uninstall/tasks/remove_host_pretasks.yml

This PR adds a new variable `falcon_windows_become` to the install, configure, and uninstall roles so that privilege escalation may be disabled if necessary.
Depending on how a Windows machine is configured and which user is used, becoming another user may be unnecessary.

feat: add toggle for become on windows

---

changelogs/fragments/fix-truthy-564.yml
roles/falcon_configure/tasks/configure.yml

Fixes #564 
There was an issue when the cid options was set to "" for it be deleted, and then it would get to this point and fail because the when clause was incorrect. A simple truthy test should provide us what we are looking for since we allow empty strings to be passed in to options for deletion purposes. 
Also added options.cid to this since it makes sense we would want to ensure both are set to use this task.

fix(falcon_configure): this task should only run when both are set

---

changelogs/fragments/add-locking.yml
changelogs/fragments/fix-truthy-564.yml
plugins/modules/sensor_download.py
roles/falcon_install/README.md
roles/falcon_install/defaults/main.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/install.yml
roles/falcon_install/tasks/preinstall.yml
roles/falcon_install/tasks/win_install.yml
roles/falcon_install/tasks/win_url.yml

Closes #567 
This feature allows multiple hosts downloading the same file to not overstep on each other as was the case before. This route improves overall download times as the module will only download a sensor at most once (assuming uniqueness) while other systems wait.
On top of that - added sane defaults (#567) for download directories to ensure we aren't creating unnecessary directories on multiple runs when a failure might occur. 
The reason for the module updates is that after additional testing when implementing the same dest dir - I noticed that each system was trying to download the same file at the same time, causing no visible improvement in time for instances where there are a large amount of hosts.

feat(sensor_download): adds lock files to prevent collision when downloading similar sensors

---

.gitignore
changelogs/fragments/578-localhost-deletion.yml
roles/falcon_install/tasks/api.yml
roles/falcon_install/tasks/cleanup.yml
roles/falcon_install/tasks/main.yml

Fixes #578
This PR addresses the issue of prematurely deleting the downloaded sensor file prior to installation. We have removed the logic to it's own task file that runs at the end of the play.

fix(falcon_install): fixes issue with deleting sensor when running locally

---

changelogs/fragments/579-fix-image-prep.yml
molecule/falcon_configure_remove_aid/verify.yml
roles/falcon_configure/tasks/configure.yml

Fixes #579
This PR introduces a fix to incorrectly using the |bool filter when working with prov tokens in master image prep. Also adding the ability to stop the sensor when working within a master image prep as to prevent the sensor from potentially updating/restarting via that cloud updates.

fix(falcon_configure): fixes issue with unwarranted bool (master image)

---

changelogs/fragments/577-decrement.yml
roles/falcon_install/tasks/api.yml

Fixes #577
This PR adds better failure message when a user uses falcon_sensor_version_decrement on newly supported linux OS's. Before, it would just fail when trying to download a sensor with an incorrect list index value.

fix(falcon_install): improves error message when using falcon_sensor_version_decrement but not enough historical sensors are available

---

changelogs/fragments/583-aid-retry.yml
roles/falcon_configure/README.md
roles/falcon_configure/defaults/main.yml
roles/falcon_configure/tasks/configure.yml

Fixes #583
This PR should address concerns about potential timeouts or "misfires" around waiting for an AID to be generated on Linux systems (particularly on Ubuntu 20.04). We've added the following to help mitigate these issues:
1. Use variables to control the retries/delays. Default to 120 seconds (12/10).

fix(falcon_configure): control aid generation wait time and logic

---

README.md

You have included the link to the "Ansible Community Code of Conduct" twice in the "Related Information" section

Duplicate "Ansible Community Code of Conduct" Link

---

README.md
changelogs/fragments/602-add-new-intel-rule.yml
plugins/modules/intel_rule_download.py
plugins/modules/intel_rule_info.py
tox.ini

Closes #587 
This PR introduces two new modules surrounding our Intel Rules:
1. `intel_rule_info` - Get information on Intel rule files based on search criteria
2. `intel_rule_download` - Download an Intel rule file

feat: new intel rule modules

---

.devcontainer/requirements.txt
.github/workflows/ansible-test.yml
.github/workflows/falcon_configure.yml
.github/workflows/falcon_configure_remove_aid.yml
.github/workflows/falcon_install.yml
.github/workflows/falcon_uninstall.yml
.github/workflows/win_falcon_configure.yml
.github/workflows/win_falcon_install.yml
.github/workflows/win_falcon_uninstall.yml

reverting back #604 since we still need to support legacy OS' that we support.. will need to figure out a better way forward to test this matrix version compat for ansible-core support

ci: invalidate pycache and use requirements.txt for devcontainer

---

changelogs/fragments/host-hide-handle-403.yml
plugins/modules/host_hide.py

My service account currently returns a 403 on this API due to lack of permissions, but this module is lacking error handling on the status code so boils up as `KeyError: 'resources'`
Given that we process hosts in batches of 100 and we add good/bad to an array, I think we should check for an explicit 403 rather than a non-200 code (as I assume the API can return other 400 status codes) - but should never return a 403 unless we don't have permissions.

Check response code
